use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets = PathBuf::from(&manifest).join("assets/skills");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_file = PathBuf::from(&out_dir).join("bundled_gen.rs");

    // Re-run if any skill file changes.
    println!("cargo:rerun-if-changed=assets/skills");

    let mut skills: Vec<(String, Vec<String>)> = Vec::new(); // (skill_name, [rel_paths])

    if assets.exists() {
        let mut dirs: Vec<_> = fs::read_dir(&assets)
            .unwrap()
            .flatten()
            .filter(|e| e.path().is_dir())
            .collect();
        dirs.sort_by_key(|e| e.file_name());

        for dir_entry in dirs {
            let skill_name = dir_entry.file_name().to_string_lossy().to_string();
            let mut rel_paths: Vec<String> = Vec::new();
            collect_rel_paths(&dir_entry.path(), &dir_entry.path(), &mut rel_paths);
            rel_paths.sort();
            skills.push((skill_name, rel_paths));
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit\n\n");
    out.push_str("pub struct BundledSkillFile {\n    pub rel_path: &'static str,\n    pub content: &'static str,\n}\n\n");
    out.push_str("pub struct BundledSkillDef {\n    pub name: &'static str,\n    pub files: &'static [BundledSkillFile],\n}\n\n");
    out.push_str("pub static BUNDLED_SKILLS: &[BundledSkillDef] = &[\n");

    for (skill_name, rel_paths) in &skills {
        out.push_str(&format!("    BundledSkillDef {{ name: {:?}, files: &[\n", skill_name));
        for rel in rel_paths {
            let abs = format!("{}/assets/skills/{}/{}", manifest, skill_name, rel);
            out.push_str(&format!(
                "        BundledSkillFile {{ rel_path: {:?}, content: include_str!({:?}) }},\n",
                rel, abs
            ));
        }
        out.push_str("    ] },\n");
    }
    out.push_str("];\n");

    fs::write(&out_file, out).unwrap();
}

fn collect_rel_paths(base: &Path, current: &Path, out: &mut Vec<String>) {
    for entry in fs::read_dir(current).unwrap().flatten() {
        let path = entry.path();
        // Use file_type() (no symlink follow) to avoid symlink cycle panics.
        if entry.file_type().map_or(false, |ft| ft.is_dir()) {
            collect_rel_paths(base, &path, out);
        } else {
            let rel = path.strip_prefix(base).unwrap();
            out.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}
